apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-gitops
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor : OpenShift
  remediationAction: enforce
policies:
  - name: openshift-gitops-installed
    manifests:
      - path: openshift-gitops-subscription.yaml
  - name: web-terminal-installed
    manifests:
      - path: web-terminal.yaml
  - name: kubeadmin-removed
    manifests:
      - path: kubeadmin-pass.yaml
    complianceType: mustnothave
  - name: gitlab-operator
    manifests:
      - path: gitlab.yaml
      

    
