apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-gitops
policyDefaults:
  namespace: policies
  placement:
    clusterSelectors:
      vendor : OpenShift
  remediationAction: enforce
policies:
  - name: vpa-operator-installed
    manifests:
      - path: vpa-autoscaler.yaml
      

    
