apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal-operator
  namespace: openshift-operators
spec:
  name: web-terminal-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
